networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none                              # Tells Docker not to look for a filesystem type (like ext4 or xfs)
      o: bind                                 # Tells the OS to use a "bind mount" (map a directory to a path)
      device: /home/aimokhta/data/mariadb     # The physical path of the volume on your host, must be absolute path
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aimokhta/data/wordpress

# Original way to implements secrets but requires messy sript line is .sh files
# secrets:
#   wp_admin_password: 
#     file: ./secrets/wp_admin_password.txt
#   wp_user_password: 
#     file: ./secrets/wp_user_password.txt


# DEPENDENCY GRAPH:
# MARIADB     =>  WORDPRESS   =>  NGINX                       (The Micro-services)
# FOUNDATION  =>  ENGINE      =>  GATEWAY                     (Conceptuals)
# Warehouse   =>  Office      =>  Front Desk & Receptionist   (Anology)
# DATABASE    =>  APP         =>  WEB SERVER/REVERSE PROXY    (What they are)
# DATA LAYER  =>  APP LAYER   =>  PRESENTATION LAYER          (TCP Layers)
services:
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb:1.0.0
    container_name: mariadb
    restart: always
    expose: 
      - "3306"
    env_file: 
      - .env
    networks: 
      - inception
    volumes: 
      - mariadb_data:/var/lib/mysql
      - ../secrets/db_admin_password.txt:/run/secrets/db_admin_password:ro
      - ../secrets/db_user_password.txt:/run/secrets/db_user_password:ro
      - ../secrets/mysql_root_password.txt:/run/secrets/mysql_root_password:ro
      - ../secrets/mysql_user_password.txt:/run/secrets/mysql_user_password:ro

  # wordpress:
  #   build: ./requirements/wordpress/.
  #   image: wordpress:1.0.0
  #   container_name: wordpress
  #   restart: always
  #   expose: 
  #     - "9000"
  #   env_file: 
  #     - .env
  #   secrets:
  #     - wp_user_password 
  #     - wp_admin_password 
  #   networks: 
  #     - inception
  #   volumes: 
  #     - wordpress_data:/var/www/html
  #     - ../secrets/wp_admin_password.txt:/run/secrets/wp_admin_password:ro
  #     - ../secrets/wp_user_password.txt:/run/secrets/wp_user_password:ro
  #   depends_on: 
  #     mariadb
          # condition: service_healthy

  # nginx:
  #   build: ./requirements/nginx/.
  #   image: nginx:1.0.0
  #   container_name: nginx
  #   restart: always
  #   ports: 
  #     - "443:443"
  #   env_file: 
  #     - .env
  #   volumes: 
  #     - wordpress_data:/var/www/html
  #   networks: 
  #     - inception
  #   depends_on: 
  #     - wordpress
