services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "8080:80"  # for testing before SSL
    volumes:
      - website_data:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wppass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception



volumes:
  website_data:

networks:
  inception:
    driver: bridge
